name: Run all programs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    name: Run all programs
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Install MemeAssembly
      run: bash .github/workflows/install_memeasm.sh 2>&1
      
    - name: Compile & Run all programs
      run: bash .github/workflows/run_all.sh 2>&1
